/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  theeradonjaroonchon
 * Created: Nov 11, 2019
 */

DROP TABLE STUDENTS;
DROP TABLE TEACHERS;
DROP TABLE SUBJECTS;
DROP TABLE QUIZ;
DROP TABLE CHOICE;

CREATE TABLE STUDENTS
(ID BIGINT NOT NULL,
FULLNAME VARCHAR(50) not null,
PASSWORD VARCHAR(25) not null,
SYEAR VARCHAR(25) not null,
DEPARTMENT VARCHAR(25) not null,
EMAIL VARCHAR(25),
PRIMARY KEY (ID));

CREATE TABLE TEACHERS
(ID BIGINT NOT NULL,
FULLNAME VARCHAR(50) not null,
PASSWORD VARCHAR(25) not null,
OWNER_SUBJECT VARCHAR(25) not null,
DEPARTMENT VARCHAR(25) not null,
<<<<<<< HEAD
EMAIL VARCHAR(25),
PRIMARY KEY (ID));

CREATE TABLE SUBJECTS
(SUBJECT_ID VARCHAR(20) not null,
=======
EMAIL VARCHAR(25) not null,
PRIMARY KEY (ID));

CREATE TABLE SUBJECTS
(SUBJECT_ID VARCHAR(20) NOT NULL,
>>>>>>> origin/master
NAME VARCHAR(25) NOT NULL,
T_ID VARCHAR(25) NOT NULL,
DETAILS VARCHAR(150) NOT NULL,
PRIMARY KEY (SUBJECT_ID));

CREATE TABLE QUIZ
(QUIZ_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
QUIZ_NAME VARCHAR(50) NOT NULL,
QUIZ_DETAILS VARCHAR(25) NOT NULL,
SUBJECT_ID VARCHAR(20) NOT NULL,
PRIMARY KEY (QUIZ_ID));

CREATE TABLE CHOICE
(CHOICE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
CHOICE_DETAILS VARCHAR(50) NOT NULL,
QUIZ_ID VARCHAR(25) NOT NULL,
CHOICE_ANSWER VARCHAR(25) DEFAULT 'FALSE' NOT NULL,
PRIMARY KEY (CHOICE_ID))


